// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID                int64              `json:"id"`
	AuthorID          uuid.UUID          `json:"authorID"`
	PostID            int64              `json:"postID"`
	ParentID          *int64             `json:"parentID,omitempty"`
	Text              string             `json:"text"`
	CreateDate        time.Time          `json:"createDate"`
	RepliesConnection *CommentConnection `json:"repliesConnection"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Node   *Comment `json:"node"`
	Cursor string   `json:"cursor"`
}

type CommentInput struct {
	AuthorID uuid.UUID `json:"authorID"`
	PostID   int64     `json:"postID"`
	ParentID *int64    `json:"parentID,omitempty"`
	Text     string    `json:"text"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID                 int64              `json:"id"`
	AuthorID           uuid.UUID          `json:"authorID"`
	Title              string             `json:"title"`
	Text               string             `json:"text"`
	CreateDate         time.Time          `json:"createDate"`
	CommentsEnabled    bool               `json:"commentsEnabled"`
	CommentsConnection *CommentConnection `json:"commentsConnection"`
}

type PostInput struct {
	AuthorID        uuid.UUID `json:"authorID"`
	Title           string    `json:"title"`
	Text            string    `json:"text"`
	CommentsEnabled bool      `json:"commentsEnabled"`
}

type Query struct {
}

type Subscription struct {
}
